<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://api.malga.io/v1';

    /**
     * The base Uri for API calls
     * @var string
     */
    public static $TEST_BASEURI = 'https://sandbox-api.malga.io/v1';


    /**
     * The username to use with basic authentication
     * @var string
     */
    public static $basicAuthUserName = 'TODO: Replace';

    /**
     * The password to use with basic authentication
     * @var string
     */
    public static $basicAuthPassword = 'TODO: Replace';

    /**
     * client id
     * @var string
     */
    public static $clientId = 'TODO: Replace';

    /**
     * secret key
     * @var string
     */
    public static $secretKey = 'TODO: Replace';
}
