<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Request for creating an order
 */
class CreateOrderRequest implements JsonSerializable
{
    /**
     * The merchant id
     * @required
     * @var string $merchantId public property
     */
    public $merchantId;

    /**
     * The order code
     * @required
     * @var string $orderId public property
     */
    public $orderId;

    /**
     *
     * @var float
     */
    public $amount;

    /**
     * The customer id
     * @required
     * @maps customer_id
     * @var string $customerId public property
     */
    public $customerId;

    /**
     * The statement Descriptor
     * @required
     * @var string $statementDescriptor public property
     */
    public $statementDescriptor;

    /**
     * The statement Descriptor
     * @required
     * @var string $statementDescriptor public property
     */
    public $capture;

    /**
     * Payment method data
     * @required
     * @var \PlugHacker\PlugAPILib\Models\CreatePaymentMethodRequest[] $paymentMethod public property
     */
    public $paymentMethod;

    /**
     * Payment source data
     * @required
     * @var \PlugHacker\PlugAPILib\Models\CreatePaymentSourceRequest[] $paymentSource public property
     */
    public $paymentSource;

    /**
     * Metadata
     * @required
     * @var array $metadata public property
     */
    public $metadata;

    public function __construct()
    {
        switch (func_num_args()) {
            case 7:
                $this->merchantId = func_get_arg(0);
                $this->amount = func_get_arg(1);
                $this->statementDescriptor = func_get_arg(2);
                $this->capture = func_get_arg(3);
                $this->paymentMethod = func_get_arg(4);
                $this->paymentSource = func_get_arg(5);
                $this->orderId = func_get_arg(6);
                break;

            default:
                $this->capture = false;
                break;
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['merchantId']             = $this->merchantId;
        $json['orderId']                = $this->orderId;
        $json['amount']                 = $this->amount;
        $json['statementDescriptor']    = $this->statementDescriptor;
        $json['capture']                = $this->capture;
        $json['paymentMethod']          = $this->paymentMethod;
        $json['paymentSource']          = $this->paymentSource;

        return $json;
    }
}
