<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;
use PlugHacker\PlugAPILib\Utils\DateTimeHelper;

/**
 *Contains information to create a pix payment
 */
class CreatePixPaymentRequest implements JsonSerializable
{
    /**
     * Datetime when pix payment will expire
     * @maps expires_at
     * @factory \PlugHacker\PlugAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     * @var \DateTime|null $expiresAt public property
     */
    public $expiresAt;

    /**
     * Seconds until pix payment expires
     * @maps expires_in
     * @var integer|null $expiresIn public property
     */
    public $expiresIn;

    /**
     * Pix additional information
     * @maps additional_information
     * @var \PlugHacker\PlugAPILib\Models\PixAdditionalInformation[]|null $additionalInformation public property
     */
    public $additionalInformation;

    /**
     * Payment method data
     * @required
     * @var \PlugHacker\PlugAPILib\Models\CreatePaymentMethodPixRequest[] $paymentMethod public property
     */
    public $paymentMethod;

    /**
     * Payment source data
     * @required
     * @var \PlugHacker\PlugAPILib\Models\CreatePaymentSourcePixRequest[] $paymentSource public property
     */
    public $paymentSource;

    /**
     * Constructor to set initial or default values of member properties
     * @param \DateTime $expiresAt             Initialization value for $this->expiresAt
     * @param integer   $expiresIn             Initialization value for $this->expiresIn
     * @param array     $additionalInformation Initialization value for $this->additionalInformation
     * @param array     $paymentMethod Initialization value for $this->paymentMethod
     * @param array     $paymentSource Initialization value for $this->paymentSource
     */
    public function __construct()
    {
        if (5 == func_num_args()) {
            $this->expiresAt                = func_get_arg(0);
            $this->expiresIn                = func_get_arg(1);
            $this->additionalInformation    = func_get_arg(2);
            $this->paymentMethod            = func_get_arg(3);
            $this->paymentSource            = func_get_arg(4);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['expires_at'] = isset($this->expiresAt) ? DateTimeHelper::toRfc3339DateTime($this->expiresAt) : null;
        $json['expires_in'] = $this->expiresIn;
        $json['additional_information'] = $this->additionalInformation;
        $json['paymentMethod'] = $this->paymentMethod;
        $json['paymentSource'] = $this->paymentSource;

        return $json;
    }
}
