<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *The ApplePay header request
 */
class CreateApplePayHeaderRequest implements JsonSerializable
{
    /**
     * SHA–256 hash, Base64 string codified
     * @maps client_id_hash
     * @var string|null $ClientIdHash public property
     */
    public $clientIdHash;

    /**
     * X.509 encoded key bytes, Base64 encoded as a string
     * @required
     * @maps ephemeral_client_id
     * @var string $ephemeralClientId public property
     */
    public $ephemeralClientId;

    /**
     * Transaction identifier, generated on Device
     * @maps transaction_id
     * @var string|null $transactionId public property
     */
    public $transactionId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $clientIdHash      Initialization value for $this->clientIdHash
     * @param string $ephemeralClientId Initialization value for $this->ephemeralClientId
     * @param string $transactionId      Initialization value for $this->transactionId
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->clientIdHash      = func_get_arg(0);
            $this->ephemeralClientId = func_get_arg(1);
            $this->transactionId      = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['client_id_hash']      = $this->clientIdHash;
        $json['ephemeral_client_id'] = $this->ephemeralClientId;
        $json['transaction_id']       = $this->transactionId;

        return $json;
    }
}
