<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Payment data
 */
class CreatePaymentMethodRequest implements JsonSerializable
{
    /**
     * Payment type
     * @required
     * @maps payment_type
     * @var string $paymentType public property
     */
    public $paymentType;

    /**
     * Instructions
     * @maps instructions
     * @var int|null $installments public property
     */
    public $installments;

    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->paymentType      = func_get_arg(0);
            $this->installments     = func_get_arg(1);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize(): mixed
    {
        $json = array();
        $json['paymentType']    = $this->paymentType;
        $json['installments']   = $this->installments;

        return $json;
    }
}
