<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Payment data
 */
class CreatePaymentMethodPixRequest implements JsonSerializable
{
    /**
     * Payment type
     * @required
     * @maps payment_type
     * @var string $paymentType public property
     */
    public $paymentType;

    /**
     * Expires In
     * @maps expiresIn
     * @var integer|null $expiresIn public property
     */
    public $expiresIn;

    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->paymentType      = func_get_arg(0);
            $this->expiresIn     = func_get_arg(1);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize(): mixed
    {
        $json = array();
        $json['paymentType']    = $this->paymentType;
        $json['expiresIn']   = $this->expiresIn;

        return $json;
    }
}
