<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *The GooglePay header request
 */
class CreateGooglePayHeaderRequest implements JsonSerializable
{
    /**
     * X.509 encoded key bytes, Base64 encoded as a string
     * @required
     * @maps ephemeral_client_id
     * @var string $ephemeralClientId public property
     */
    public $ephemeralClientId;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $ephemeralClientId Initialization value for $this->ephemeralClientId
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->ephemeralClientId = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['ephemeral_client_id'] = $this->ephemeralClientId;

        return $json;
    }
}
