<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Payment data
 */
class CreatePaymentMethodBoletoRequest implements JsonSerializable
{
    /**
     * Payment type
     * @required
     * @maps payment_type
     * @var string $paymentType public property
     */
    public $paymentType;

    /**
     * Expires Date
     * @maps expiresDate
     * @var string|null $expiresDate public property
     */
    public $expiresDate;

    /**
     * Instructions
     * @maps instructions
     * @var int|null $installments public property
     */
    public $instructions;

    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->paymentType      = func_get_arg(0);
            $this->expiresDate     = func_get_arg(1);
            $this->instructions     = func_get_arg(2);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['paymentType']    = $this->paymentType;
        $json['expiresDate']   = $this->expiresDate;
        $json['instructions']   = $this->instructions;

        return $json;
    }
}
