<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;
use PlugHacker\PlugCore\Payment\Aggregates\Customer;

/**
 *Payment data
 */
class CreatePaymentSourcePixRequest implements JsonSerializable
{
    /**
     * Payment type
     * @required
     * @maps source_type
     * @var string $sourceType public property
     */
    public $sourceType;

    /**
     * Customer source data
     * @required
     * @var Customer $customer public property
     */
    public $customer;

    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->sourceType   = func_get_arg(0);
            $this->customer      = func_get_arg(1);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['sourceType'] = $this->sourceType;
        $json['customer']     = $this->customer;

        return $json;
    }
}
