<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Response object for getting the shipping data
 */
class GetPaymentSourceResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var string $sourceType public property
     */
    public $sourceType;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $cardId public property
     */
    public $cardId;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $tokenId public property
     */
    public $tokenId;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
        if (3 == func_num_args()) {
            $this->sourceType = func_get_arg(0);
            $this->cardId  = func_get_arg(1);
            $this->tokenId  = func_get_arg(2);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['sourceType']   = $this->sourceType;
        $json['cardId']    = $this->cardId;
        $json['tokenId']    = $this->tokenId;
        return $json;
    }
}
