<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;

/**
 *Response object for getting the shipping data
 */
class GetPaymentMethodResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @var integer $installments public property
     */
    public $installments;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $paymentType public property
     */
    public $paymentType;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $expiresIn public property
     */
    public $expiresIn;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $qrCodeData public property
     */
    public $qrCodeData;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $qrCodeImageUrl public property
     */
    public $qrCodeImageUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $expiresDate public property
     */
    public $expiresDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $barcodeData public property
     */
    public $barcodeData;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $barcodeImageUrl public property
     */
    public $barcodeImageUrl;

    /**
     * Constructor to set initial or default values of member properties
     */
    public function __construct()
    {
        if (8 == func_num_args()) {
            $this->installments = func_get_arg(0);
            $this->paymentType  = func_get_arg(1);
            $this->expiresIn  = func_get_arg(2);
            $this->qrCodeData  = func_get_arg(3);
            $this->qrCodeImageUrl  = func_get_arg(4);
            $this->expiresDate  = func_get_arg(5);
            $this->barcodeData  = func_get_arg(6);
            $this->barcodeImageUrl  = func_get_arg(7);
        }
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['installments']   = $this->installments;
        $json['paymentType']    = $this->paymentType;
        $json['expiresIn']      = $this->expiresIn;
        $json['qrCodeData']     = $this->qrCodeData;
        $json['qrCodeImageUrl'] = $this->qrCodeImageUrl;
        $json['expiresDate']    = $this->expiresDate;
        $json['barcodeData']    = $this->barcodeData;
        $json['barcodeImageUrl'] = $this->barcodeImageUrl;

        return $json;
    }
}
