<?php
/*
 * PlugAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace PlugHacker\PlugAPILib\Models;

use JsonSerializable;
use PlugHacker\PlugAPILib\Utils\DateTimeHelper;

/**
 *Response object when getting a pix transaction
 *
 * @discriminator transaction_type
 * @discriminatorType pix
 */
class GetPixTransactionResponse extends GetTransactionResponse implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @required
     * @maps qr_code_data
     * @var string $qrCodeData public property
     */
    public $qrCodeData;

    /**
     * @todo Write general description for this property
     * @required
     * @maps qrCodeImageUrl
     * @var string $qrCodeImageUrl public property
     */
    public $qrCodeImageUrl;

    /**
     * @todo Write general description for this property
     * @required
     * @maps expires_at
     * @factory \PlugHacker\PlugAPILib\Utils\DateTimeHelper::fromRfc3339DateTime
     * @var \DateTime $expiresAt public property
     */
    public $expiresAt;

    /**
     * @todo Write general description for this property
     * @required
     * @maps additional_information
     * @var \PlugHacker\PlugAPILib\Models\PixAdditionalInformation[] $additionalInformation public property
     */
    public $additionalInformation;

    /**
     * Constructor to set initial or default values of member properties
     * @param string    $qrCodeData                Initialization value for $this->qrCodeData
     * @param string    $qrCodeImageUrl             Initialization value for $this->qrCodeImageUrl
     * @param \DateTime $expiresAt             Initialization value for $this->expiresAt
     * @param array     $additionalInformation Initialization value for $this->additionalInformation
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->qrCodeData                = func_get_arg(0);
            $this->qrCodeImageUrl             = func_get_arg(1);
            $this->expiresAt             = func_get_arg(2);
            $this->additionalInformation = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['qr_code_data']                = $this->qrCodeData;
        $json['qr_code_image_url']            = $this->qrCodeImageUrl;
        $json['expires_at']             = DateTimeHelper::toRfc3339DateTime($this->expiresAt);
        $json['additional_information'] = $this->additionalInformation;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}
